golgolz/recruit-app

src/main/webapp/user/findMail.jsp, src/main/webapp/user/findMailComplete.jsp, src/main/webapp/user/findPass.jsp, src/main/webapp/user/findPassComplete.jsp, src/main/webapp/user/login.jsp, src/main/webapp/user/signup.jsp
design : 로그인,회원가입,계정찾기,계정찾기성공,비밀번호 찾기 디자인 화면 추가
=> design : 로그인,회원가입,계정찾기,계정찾기성공,비밀번호 찾기 디자인 화면 추가

src/main/webapp/user/mypage/mypageApply.jsp, src/main/webapp/user/mypage/mypageCareer.jsp
design : 마이 페이지 레이아웃 통일, 디자인 수정
=> design : 마이 페이지 레이아웃 통일, 디자인 수정

src/main/webapp/user/mypage/mypageQNAList.jsp, src/main/webapp/user/mypage/mypageReview.jsp, src/main/webapp/user/mypage/mypageWriteQNA.jsp
design: 마이페이지 Career,review 화면 디자인 추가, 문의 작성,리스트 파일 추가
=> design: 마이페이지 Career,review 화면 디자인 추가, 문의 작성,리스트 파일 추가

src/main/webapp/user/mypage/modifyUserInfo.jsp, src/main/webapp/user/mypage/mypageApply.jsp, src/main/webapp/user/mypage/mypageReview.jsp, src/main/webapp/user/mypage/mypageUserInfo.jsp, src/main/webapp/user/mypage/mypage_layout.jsp, src/main/webapp/user/signup.jsp
design : 마이 페이지 레이아웃 링크 수정, 회원 정보 변경 디자인 화면 추가
=> design : 마이 페이지 레이아웃 링크 수정, 회원 정보 변경 디자인 화면 추가

src/main/webapp/user/mypage/checkPass.jsp, src/main/webapp/user/mypage/modifyPass.jsp
design : 비밀번호 확인, 비밀번호 재설정 화면 디자인 추가
=> design : 비밀번호 확인, 비밀번호 재설정 화면 디자인 추가

src/main/webapp/manage/adminLogin/adminLogin.jsp
=> design : 관리자 로그인 화면 디자인 추가

src/main/webapp/companyInfo/user_company_detail.jsp
=> design: 피드백 받은 내용 수정

src/main/webapp/manage/admin/admins.jsp, src/main/webapp/manage/user/detail.jsp, src/main/webapp/manage/user/users.jsp, src/main/webapp/user/signup2.jsp
design : 관리자 사용자 관리 데이터 마스킹 처리, 회원가입 페이지 분리
=> design : 관리자 사용자 관리 데이터 마스킹 처리, 회원가입 페이지 분리

src/main/webapp/assets/css/mypage.css, src/main/webapp/user/mypage/mypageCareer.jsp, src/main/webapp/user/mypage/mypageReview.jsp, src/main/webapp/user/mypage/mypageUserInfo.jsp, src/main/webapp/user/mypage/qna/mypageQNADetail.jsp, src/main/webapp/user/mypage/qna/mypageQNAList.jsp, src/main/webapp/user/mypage/qna/mypageWriteQNA.jsp
=> design : 마이페이지 레이아웃 조정

src/main/webapp/manage/company/companies.jsp, src/main/webapp/manage/dashboard/dashboard.jsp, src/main/webapp/manage/notice/notices.jsp, src/main/webapp/manage/qna/qnas.jsp
기업리스트 / 대시보드 / 문의사항 관리 / 공지사항 관리 레이아웃 수정
=> design : 관리자 페이지 컨텐츠 레이아웃 수정

src/main/webapp/assets/css/recruit/rcr-sv-202405271315.css, src/main/webapp/notice/notice_detail.jsp, src/main/webapp/user/mypage/modifyPass.jsp, src/main/webapp/user/mypage/modifyUserInfo.jsp
=> design : 헤더 a태그 색상 통일

src/main/webapp/assets/css/find_user_info.css, src/main/webapp/assets/css/mypage.css, src/main/webapp/assets/css/signup.css, src/main/webapp/assets/css/user_login.css, src/main/webapp/user/findPass.jsp, src/main/webapp/user/findPassComplete.jsp, src/main/webapp/user/login.jsp, src/main/webapp/user/mypage/modifyPass.jsp, src/main/webapp/user/mypage/modifyUserInfo.jsp, src/main/webapp/user/mypage/mypageApply.jsp, src/main/webapp/user/mypage/mypageCareer.jsp, src/main/webapp/user/mypage/mypageReview.jsp, src/main/webapp/user/mypage/mypageUserInfo.jsp, src/main/webapp/user/signup.jsp, src/main/webapp/user/signup2.jsp
=> design : 사용자 레이아웃 수정

src/main/webapp/manage/admin/admins.jsp, src/main/webapp/manage/user/detail.jsp, src/main/webapp/manage/user/users.jsp
=> design : 관리자 페이지 버튼 스타일 적용

src/main/webapp/user/login.jsp, src/main/webapp/user/mypage/modifyPass.jsp, src/main/webapp/user/mypage/modifyUserInfo.jsp, src/main/webapp/user/mypage/mypageCareer.jsp, src/main/webapp/user/mypage/mypageReview.jsp
=> design : 사용자 마이페이지 버튼 디자인 통일

src/main/webapp/manage/user/users.jsp, src/main/webapp/user/login.jsp, src/main/webapp/user/signup.jsp
feat : 로그인 유효성 검증, 회원가입 이메일, 비밀번호 확인 체크 scipt 코드 추가
=> feat : 로그인 유효성 검증, 회원가입 이메일, 비밀번호 확인 체크 scipt 코드 추가

src/main/webapp/user/signup.jsp
=> feat : 회원가입 유효성 검증 스크립트 코드 추가

src/main/webapp/user/findMail.jsp, src/main/webapp/user/findMailComplete.jsp, src/main/webapp/user/login.jsp, src/main/webapp/user/signup.jsp, src/main/webapp/user/signup2.jsp
feat : 로그인, 회원가입 링크 연결, 회원가입 2페이지 스크립트 코드 추가
=> feat : 로그인, 회원가입 링크 연결, 회원가입 2페이지 스크립트 코드 추가

src/main/webapp/user/findMail.jsp, src/main/webapp/user/findPass.jsp, src/main/webapp/user/findPassComplete.jsp, src/main/webapp/user/signup.jsp
feat : 계정 찾기, 비밀번호 찾기 유효성 검증 스크립트 코드 추가, 결과 화면 링크 연결
=> feat : 계정 찾기, 비밀번호 찾기 유효성 검증 스크립트 코드 추가, 결과 화면 링크 연결

src/main/webapp/manage/adminLogin/adminLogin.jsp, src/main/webapp/manage/user/users.jsp, src/main/webapp/user/mypage/modifyPass.jsp, src/main/webapp/user/mypage/modifyUserInfo.jsp, src/main/webapp/user/mypage/mypageApply.jsp, src/main/webapp/user/mypage/mypageCareer.jsp, src/main/webapp/user/mypage/mypageReview.jsp, src/main/webapp/user/mypage/mypageUserInfo.jsp, src/main/webapp/user/mypage/mypage_layout.jsp
feat : 사용자 마이페이지, 관리자 로그인, 사용자 관리-상세조회 링크 연결
=> feat : 사용자 마이페이지, 관리자 로그인, 사용자 관리-상세조회 링크 연결

src/main/java/kr/co/sist/admin/controller/qna/QnaAdminController.java, src/main/java/kr/co/sist/admin/dao/qna/QnaAdminDAO.java, src/main/java/kr/co/sist/admin/domain/qna/QnaDomain.java, src/main/java/kr/co/sist/admin/service/qna/QnaAdminService.java, src/main/java/kr/co/sist/mapper/admin/qna/QnaMapper.xml, src/main/java/kr/co/sist/mapper/qna/UserQnamapper.xml, src/main/webapp/manage/qna/answer_frm.jsp, src/main/webapp/manage/qna/new_detail.jsp, src/main/webapp/manage/qna/new_qnas.jsp, src/main/webapp/manage/qna/old_detail.jsp, src/main/webapp/manage/qna/qnas.jsp
feat : qna domain, controller, service, dao생성
=> design : 관리자 페이지네이션 수정, 스크롤 수정

src/main/java/kr/co/sist/admin/vo/recruit/SearchVO.java, src/main/java/kr/co/sist/mapper/admin/recruit/recruitMapper.xml, src/main/webapp/assets/css/manage/goods/general.css, src/main/webapp/assets/css/manage/notice/optimizer_user.css, src/main/webapp/assets/css/manage/order/admin.css, src/main/webapp/assets/css/manage/order/reset.css, src/main/webapp/assets/css/material-dashboard.min.css, src/main/webapp/assets/layout/admin/header.jsp, src/main/webapp/assets/layout/user/header.jsp, src/main/webapp/assets/layout/user/lib.jsp, src/main/webapp/manage/admin/admins.jsp, src/main/webapp/manage/company/companies.jsp, src/main/webapp/manage/dashboard/dashboard.jsp, src/main/webapp/manage/notice/notices.jsp, src/main/webapp/manage/notice/notices_detail.jsp, src/main/webapp/manage/notice/notices_write.jsp, src/main/webapp/manage/qna/qnas.jsp, src/main/webapp/manage/recruit/recruits.jsp, src/main/webapp/manage/recruit/resume/detail.jsp, src/main/webapp/manage/recruit/resume/resumes.jsp, src/main/webapp/manage/review/reviews.jsp, src/main/webapp/manage/user/users.jsp, src/main/webapp/recruit/recruits.jsp
1. 사용자 페이지 링크 연결
2. 관리자 페이지 네브바, 검색 인풋 레이아웃 조정
3. 관리자 페이지 리스트 레이아웃 조정
4. 관리자 공지사항 상세, 등록페이지 레이아웃 조정 및 optimize_user.css 파일화
=> design : 사용자 링크 연결, 관리자 레이아웃 조정

src/main/java/kr/co/sist/admin/controller/admin/AdminManageController.java, src/main/java/kr/co/sist/admin/dao/admin/AdminManageDAO.java, src/main/java/kr/co/sist/admin/service/admin/AdminManageService.java, src/main/java/kr/co/sist/admin/vo/admin/LoginVO.java, src/main/java/kr/co/sist/mapper/admin/admin/adminMapper.xml, src/main/java/kr/co/sist/properties/mybatis-config.xml, src/main/webapp/manage/adminLogin/adminLogin.jsp, src/main/webapp/manage/user/detail.jsp
feat : AdminMange java 패키지 파일 구성, mapper 추가
=> feat : AdminMange java 패키지 파일 구성, mapper 추가

src/main/java/kr/co/admin/dao/companyinfo/CompanyinfoAdminDAO.java, src/main/java/kr/co/admin/dao/notice/NoticeAdminDAO.java, src/main/java/kr/co/admin/domain/notice/NoticeAdminDomain.java, src/main/java/kr/co/admin/mapper/companyinfo/companyinfoAdminMapper.xml, src/main/java/kr/co/admin/mapper/notice/noticeAdminMapper.xml, src/main/java/kr/co/admin/service/companyinfo/CompanyinfoAdminService.java, src/main/java/kr/co/admin/service/notice/NoticeAdminService.java, src/main/java/kr/co/admin/vo/notice/NoticeAdminVO.java, src/main/java/kr/co/admin/vo/notice/SearchVO.java, src/main/java/kr/co/sist/admin/controller/companyinfo/CompanyinfoAdminController.java, src/main/java/kr/co/sist/domain/companyinfo/CompanyinfoDomain.java, src/main/java/kr/co/sist/user/controller/companyinfo/CompanyinfoUserController.java, src/main/java/kr/co/sist/user/dao/companyinfo/CompanyinfoUserDAO.java, src/main/java/kr/co/sist/user/mapper/companyinfo/companyinfoUserMapper.xml, src/main/java/kr/co/sist/user/service/companyinfo/CompanyinfoUserService.java, src/main/java/kr/co/sist/vo/companyinfo/CompanyinfoVO.java, src/main/java/kr/co/sist/vo/companyinfo/SearchVO.java, src/main/webapp/assets/css/material-dashboard.min.css
feat: 기업정보 mapper 구성, 필요한 mapper, service, controller, dao, domain, vo 파일 및 패키지 구성
=> design: css파일 수정 (페이지네이션 radius 조정, 검색버튼 수정)

src/main/java/kr/co/sist/admin/controller/admin/AdminManageController.java, src/main/webapp/manage/adminLogin/adminLogin.jsp, src/main/webapp/user/mypage/modifyUserInfo.jsp
=> feat: 사용자 보안 질문 모달창 추가

src/main/webapp/manage/admin/admins.jsp, src/main/webapp/manage/adminLogin/adminLogin.jsp, src/main/webapp/manage/user/users.jsp, src/main/webapp/user/mypage/checkPass.jsp, src/main/webapp/user/mypage/modifyUserInfo.jsp
feat : 관리자 권한 변경, 관리자 등록 모달 창 추가, 사용자 관리, 관리자 관리 화면 페이지네이션 디자인 추가
=> feat : 관리자 권한 변경, 관리자 등록 모달 창 추가, 사용자 관리, 관리자 관리 화면 페이지네이션 디자인 추가

pom.xml, src/main/java/kr/co/sist/admin/controller/admin/AdminManageController.java, src/main/java/kr/co/sist/admin/dao/admin/AdminManageDAO.java, src/main/java/kr/co/sist/admin/domain/admin/AdminInfoDomain.java, src/main/java/kr/co/sist/admin/domain/admin/LoginDomain.java, src/main/java/kr/co/sist/admin/service/admin/AdminManageService.java, src/main/java/kr/co/sist/mapper/admin/admin/adminMapper.xml, src/main/java/kr/co/sist/security/SecurityController.java, src/main/webapp/manage/admin/admins.jsp, src/main/webapp/manage/adminLogin/adminLogin.jsp, src/main/webapp/user/login.jsp, src/main/webapp/user/mypage/modifyUserInfo.jsp
feat : springframework.security dependency 추가, 암호화를 위한 패키지 구성 추가
=> feat : springframework.security dependency 추가, 암호화를 위한 패키지 구성 추가

src/main/webapp/manage/admin/admins.jsp, src/main/webapp/manage/adminLogin/adminLogin.jsp, src/main/webapp/manage/user/detail.jsp
=> design : 상세 페이지 이미지 링크 수정

src/main/java/kr/co/sist/admin/controller/qna/QnaAdminController.java, src/main/java/kr/co/sist/admin/dao/qna/QnaAdminDAO.java, src/main/java/kr/co/sist/admin/service/qna/QnaAdminService.java, src/main/java/kr/co/sist/mapper/admin/qna/QnaMapper.xml, src/main/webapp/manage/qna/new_qnas.jsp, src/main/webapp/manage/qna/qnas.jsp, src/main/webapp/notice/notices.jsp, src/main/webapp/user/mypage/qna/mypageQNAList.jsp, src/main/webapp/user/mypage/qna/mypageWriteQNA.jsp
feat : controller, dao, service, mapper구현 진행 중
=> design : 사용자, 관리자 레이아웃들 ui수정

src/main/webapp/manage/admin/admins.jsp, src/main/webapp/manage/user/detail.jsp, src/main/webapp/manage/user/users.jsp, src/main/webapp/user/signup2.jsp
feat : 회원가입 버튼 버그 수정(signupBtn id 중복 문제해결), 관리자관리 modal design 수정, 관리자 datepicker 한글화 코드 적용
=> feat : 회원가입 버튼 버그 수정(signupBtn id 중복 문제해결), 관리자관리 modal design 수정,datepciker 한글화 코드 적용

src/main/webapp/user/mypage/mypageApply.jsp, src/main/webapp/user/mypage/mypageCareer.jsp, src/main/webapp/user/mypage/mypageReview.jsp, src/main/webapp/user/signup2.jsp
design : 회원가입 주소 입력창 제거, 마이페이지 레이아웃 수정
=> design : 회원가입 주소 입력창 제거, 마이페이지 레이아웃 수정

src/main/webapp/assets/layout/user/header.jsp, src/main/webapp/assets/layout/user/lib.jsp, src/main/webapp/user/login.jsp
design : 로그인 상태/로그인 안된 상태 별 헤더 버튼 디자인/스크립트 추가
=> design : 로그인 상태/로그인 안된 상태 별 헤더 버튼 디자인/스크립트 추가

src/main/webapp/user/login.jsp, src/main/webapp/user/mypage/modifyPass.jsp, src/main/webapp/user/mypage/modifyUserInfo.jsp
feat : 사용자 정보 변경, 비밀번호 변경 유효성 검증 추가
=> feat : 사용자 정보 변경, 비밀번호 변경 유효성 검증 추가

src/main/java/kr/co/sist/admin/controller/qna/QnaAdminController.java, src/main/java/kr/co/sist/admin/dao/qna/QnaAdminDAO.java, src/main/java/kr/co/sist/admin/service/qna/QnaAdminService.java, src/main/java/kr/co/sist/mapper/admin/qna/QnaMapper.xml, src/main/webapp/notice/notices.jsp, src/main/webapp/user/mypage/qna/mypageWriteQNA.jsp
feat : qna 기능구현,,은 아직 못했고 노력중 ^^
=> design: 사용자 notice, qna ui 피드백 수정

src/main/java/kr/co/sist/properties/mybatis-config.xml
=> feat : adminMapper.xml 충돌 제거

src/main/java/kr/co/sist/user/controller/basic/UserBasicController.java, src/main/java/kr/co/sist/user/controller/mypage/MypageController.java, src/main/webapp/WEB-INF/views/user/login.jsp, src/main/webapp/WEB-INF/views/user/mypage/checkPass.jsp, src/main/webapp/WEB-INF/views/user/mypage/modifyPass.jsp, src/main/webapp/WEB-INF/views/user/mypage/modifyUserInfo.jsp, src/main/webapp/WEB-INF/views/user/mypage/mypageUserInfo.jsp, src/main/webapp/WEB-INF/views/user/mypage/mypage_layout.jsp, src/main/webapp/WEB-INF/views/user/signup.jsp, src/main/webapp/WEB-INF/views/user/signup2.jsp, src/main/webapp/assets/layout/user/lib.jsp
feat: 사용자 view 페이지 mapping 링크연결, MypageController 추가
=> feat: 사용자 view 페이지 mapping 링크연결, MypageController 추가

pom.xml, src/main/java/kr/co/sist/security/JwtProvider.java, src/main/java/kr/co/sist/security/JwtSecretKeyGenerator.java, src/main/java/kr/co/sist/security/SecurityController.java, src/main/java/kr/co/sist/security/jwt.xml, src/main/java/kr/co/sist/user/controller/basic/UserBasicController.java, src/main/java/kr/co/sist/user/vo/signup/SignupVO.java, src/main/webapp/WEB-INF/views/user/signup.jsp
=> feat : 회원가입 페이지 이동 간 JWT 추가

src/main/java/kr/co/sist/security/SecurityConfig.java, src/main/java/kr/co/sist/security/SecurityController.java, src/main/webapp/WEB-INF/views/user/signupResult.jsp
=> feat : 회원가입 시 비밀번호 암호화 기능 추가

src/main/java/kr/co/sist/admin/controller/qna/QnaAdminController.java, src/main/java/kr/co/sist/admin/dao/qna/QnaAdminDAO.java, src/main/java/kr/co/sist/admin/service/qna/QnaAdminService.java, src/main/java/kr/co/sist/mapper/admin/qna/QnaMapper.xml, src/main/java/kr/co/sist/mapper/user/notice/userNoticeMapper.xml, src/main/java/kr/co/sist/user/domain/notice/NoticeDomain.java, src/main/java/kr/co/sist/user/vo/notice/NoticeVO.java, src/main/webapp/manage/qna/answer_frm.jsp, src/main/webapp/manage/qna/old_detail.jsp, src/main/webapp/manage/qna/qnas.jsp, src/main/webapp/user/mypage/qna/mypageQNADetail.jsp, src/main/webapp/user/mypage/qna/mypageQNAList.jsp, src/main/webapp/user/mypage/qna/mypageWriteQNA.jsp
새 문의사항 답변보내기 구현 중,
design : 사용자 qna 레이아웃 수정(피드백)
=> feat : qna 답변완료된 문의사항 리스트 불러오기, 상세조회 구현

src/main/java/kr/co/sist/mapper/user/basic/userBasicMapper.xml, src/main/java/kr/co/sist/security/JwtSignupProvider.java, src/main/java/kr/co/sist/security/SecurityController.java, src/main/java/kr/co/sist/user/controller/basic/UserBasicController.java, src/main/java/kr/co/sist/user/dao/basic/UserBasicDAO.java, src/main/java/kr/co/sist/user/domain/basic/LoginDomain.java, src/main/java/kr/co/sist/user/service/basic/UserBasicService.java, src/main/webapp/WEB-INF/views/user/login.jsp, src/main/webapp/WEB-INF/views/user/signup.jsp
=> feat : 회원가입 시 이메일 중복 확인 기능 추가

src/main/java/kr/co/sist/mapper/user/basic/userBasicMapper.xml, src/main/java/kr/co/sist/security/SecurityController.java, src/main/java/kr/co/sist/user/controller/basic/UserBasicController.java, src/main/java/kr/co/sist/user/dao/basic/UserBasicDAO.java, src/main/java/kr/co/sist/user/service/basic/UserBasicService.java, src/main/webapp/WEB-INF/views/assets/layout/user/lib.jsp, src/main/webapp/WEB-INF/views/user/signup2.jsp, src/main/webapp/assets/layout/user/lib.jsp, src/main/webapp/user/signup2.jsp
List 조회로 수정feat : 회원가입 시 전화번호 format 기능 추가, 로그인 시 마지막 로그인 일시 update 기능 추가, 보안 질문 List 조회로 수정
=> feat : 회원가입 시 전화번호 format 기능 추가, 로그인 시 마지막 로그인 일시 update 기능 추가, 보안 질문

src/main/java/kr/co/sist/user/controller/basic/UserBasicController.java, src/main/java/kr/co/sist/user/service/basic/UserBasicService.java, src/main/java/kr/co/sist/user/vo/basic/FindMailVO.java, src/main/webapp/WEB-INF/views/assets/layout/user/lib.jsp, src/main/webapp/WEB-INF/views/user/findMail.jsp, src/main/webapp/WEB-INF/views/user/findMailComplete.jsp, src/main/webapp/assets/layout/user/lib.jsp
=> feat : 계정 찾기 기능 추가

pom.xml, src/main/java/kr/co/sist/mapper/user/basic/userBasicMapper.xml, src/main/java/kr/co/sist/security/SecurityController.java, src/main/java/kr/co/sist/security/TempPasswordGenerator.java, src/main/java/kr/co/sist/user/dao/basic/UserBasicDAO.java, src/main/java/kr/co/sist/user/service/basic/UserBasicService.java, src/main/java/kr/co/sist/user/vo/basic/FindPassVO.java, src/main/java/kr/co/sist/user/vo/basic/UpdatePassVO.java, src/main/webapp/WEB-INF/views/user/findPass.jsp, src/main/webapp/WEB-INF/views/user/findPassComplete.jsp, src/main/webapp/user/findPass.jsp
feat : 비밀번호 난수 생성 로직, 임시 비밀번호 발급, 비밀번호 변경, 비밀번호 재설정 플래그 설정 추가
=> feat : 비밀번호 난수 생성 로직, 임시 비밀번호 발급, 비밀번호 변경, 비밀번호 재설정 플래그 설정 추가

src/main/java/kr/co/sist/mapper/user/mypage/mypageMapper.xml, src/main/java/kr/co/sist/properties/mybatis-config.xml, src/main/java/kr/co/sist/security/SecurityController.java, src/main/java/kr/co/sist/security/TempPasswordGenerator.java, src/main/java/kr/co/sist/user/controller/mypage/MypageController.java, src/main/java/kr/co/sist/user/dao/basic/UserBasicDAO.java, src/main/java/kr/co/sist/user/dao/mypage/MypageDAO.java, src/main/java/kr/co/sist/user/domain/mypage/UserInfoDomain.java, src/main/java/kr/co/sist/user/service/mypage/MypageService.java, src/main/java/kr/co/sist/user/vo/mypage/CheckPassVO.java, src/main/java/kr/co/sist/user/vo/mypage/UserInfoVO.java, src/main/webapp/WEB-INF/views/user/findPass.jsp, src/main/webapp/WEB-INF/views/user/findPassComplete.jsp, src/main/webapp/WEB-INF/views/user/login.jsp, src/main/webapp/WEB-INF/views/user/mypage/checkPass.jsp, src/main/webapp/WEB-INF/views/user/mypage/modifyPass.jsp, src/main/webapp/WEB-INF/views/user/mypage/modifyPassProcess.jsp, src/main/webapp/WEB-INF/views/user/mypage/modifyUserInfo.jsp, src/main/webapp/WEB-INF/views/user/mypage/mypageUserInfo.jsp
=> feat : 마이 페이지 내 비밀번호 변경 기능 구현

src/main/java/kr/co/sist/mapper/user/mypage/mypageMapper.xml, src/main/java/kr/co/sist/security/SecurityController.java, src/main/java/kr/co/sist/user/controller/mypage/MypageController.java, src/main/java/kr/co/sist/user/dao/mypage/MypageDAO.java, src/main/java/kr/co/sist/user/service/basic/UserBasicService.java, src/main/java/kr/co/sist/user/service/mypage/MypageService.java, src/main/java/kr/co/sist/user/vo/mypage/UpdateUserVO.java, src/main/webapp/WEB-INF/views/user/mypage/checkPass.jsp, src/main/webapp/WEB-INF/views/user/mypage/modifyUserInfo.jsp, src/main/webapp/WEB-INF/views/user/mypage/modifyUserProcess.jsp
=> feat : 회원정보 수정 기능 추가

src/main/java/kr/co/sist/admin/controller/basic/AdminBasicController.java, src/main/java/kr/co/sist/mapper/user/mypage/mypageMapper.xml, src/main/java/kr/co/sist/user/controller/mypage/MypageController.java, src/main/java/kr/co/sist/user/dao/mypage/MypageDAO.java, src/main/java/kr/co/sist/user/domain/mypage/UserApplyDomain.java, src/main/java/kr/co/sist/user/service/mypage/MypageService.java, src/main/webapp/WEB-INF/views/assets/layout/admin/header.jsp, src/main/webapp/WEB-INF/views/manage/admin/admins.jsp, src/main/webapp/WEB-INF/views/manage/adminLogin/adminLogin.jsp, src/main/webapp/WEB-INF/views/manage/user/detail.jsp, src/main/webapp/WEB-INF/views/manage/user/users.jsp, src/main/webapp/WEB-INF/views/user/mypage/mypageApply.jsp, src/main/webapp/assets/layout/admin/header.jsp
feat : 마이페이지 내 사용자 지원 현황 리스트 조회 기능 추가
=> feat : 마이페이지 내 사용자 지원 현황 리스트 조회 기능 추가

src/main/java/kr/co/sist/mapper/user/mypage/mypageMapper.xml, src/main/java/kr/co/sist/user/controller/mypage/MypageController.java, src/main/java/kr/co/sist/user/dao/mypage/MypageDAO.java, src/main/java/kr/co/sist/user/domain/mypage/UserCareerDomain.java, src/main/java/kr/co/sist/user/domain/mypage/UserReviewDomain.java, src/main/java/kr/co/sist/user/service/mypage/MypageService.java, src/main/webapp/WEB-INF/views/user/mypage/mypageApply.jsp, src/main/webapp/WEB-INF/views/user/mypage/mypageCareer.jsp, src/main/webapp/WEB-INF/views/user/mypage/mypageReview.jsp
feat: 마이페이지 사용자 커리어, 리뷰 조회 로직 구현
=> feat: 마이페이지 사용자 커리어, 리뷰 조회 로직 구현

src/main/java/kr/co/sist/admin/controller/basic/AdminBasicController.java, src/main/java/kr/co/sist/admin/dao/basic/AdminBasicDAO.java, src/main/java/kr/co/sist/admin/domain/basic/AdminLoginDomain.java, src/main/java/kr/co/sist/admin/service/basic/AdminBasicService.java, src/main/java/kr/co/sist/admin/vo/basic/AdminLoginVO.java, src/main/java/kr/co/sist/admin/vo/basic/InsertAdminVO.java, src/main/java/kr/co/sist/mapper/admin/basic/adminMapper.xml, src/main/java/kr/co/sist/properties/mybatis-config.xml, src/main/java/kr/co/sist/security/SecurityController.java, src/main/java/kr/co/sist/user/controller/basic/UserBasicController.java, src/main/webapp/WEB-INF/views/manage/adminLogin/adminLogin.jsp, src/main/webapp/WEB-INF/views/user/findMailComplete.jsp, src/main/webapp/WEB-INF/views/user/findPassComplete.jsp, src/main/webapp/WEB-INF/views/user/mypage/mypageUserInfo.jsp
feat: 계정/비번 찾기 페이지 만료 기능 추가(새로고침, 뒤로가기 불가)
=> feat: 계정/비번 찾기 페이지 만료 기능 추가(새로고침, 뒤로가기 불가)

src/main/java/kr/co/sist/admin/controller/qna/QnaAdminController.java, src/main/java/kr/co/sist/mapper/admin/qna/QnaMapper.xml, src/main/java/kr/co/sist/mapper/user/notice/noticeMapper.xml, src/main/java/kr/co/sist/mapper/user/qna/qnaMapper.xml, src/main/java/kr/co/sist/user/controller/notice/NoticeUserContoller.java, src/main/java/kr/co/sist/user/dao/notice/NoticeUserDAO.java, src/main/java/kr/co/sist/user/service/notice/NoticeUserService.java, src/main/webapp/WEB-INF/views/notice/notices.jsp, src/main/webapp/notice/notices.jsp
=> feat : notice user 카테고리별 검색 기능 구현

src/main/java/kr/co/sist/admin/controller/basic/AdminBasicController.java, src/main/java/kr/co/sist/admin/dao/basic/AdminBasicDAO.java, src/main/java/kr/co/sist/admin/service/basic/AdminBasicService.java, src/main/java/kr/co/sist/admin/vo/basic/SearchVO.java, src/main/java/kr/co/sist/mapper/admin/basic/adminMapper.xml, src/main/webapp/WEB-INF/views/manage/admin/admins.jsp
feat:관리자 관리 페이지 리스트 조회,검색,추가 기능 구현
=> feat:관리자 관리 페이지 리스트 조회,검색,추가 기능 구현

src/main/java/kr/co/sist/mapper/user/notice/noticeMapper.xml, src/main/java/kr/co/sist/user/controller/notice/NoticeUserContoller.java, src/main/java/kr/co/sist/user/dao/notice/NoticeUserDAO.java, src/main/java/kr/co/sist/user/service/notice/NoticeUserService.java, src/main/java/kr/co/sist/user/vo/notice/SearchVO.java
=> feat : 공지사항 카테고리 항목 전체 목록 불러오기 수정

src/main/java/kr/co/sist/admin/dao/basic/AdminBasicDAO.java, src/main/java/kr/co/sist/mapper/admin/basic/adminMapper.xml, src/main/webapp/WEB-INF/views/manage/admin/admins.jsp
feat: 관리자 추가 기능 수정, 페이지네이션 버그 수정
=> feat: 관리자 추가 기능 수정, 페이지네이션 버그 수정

src/main/java/kr/co/sist/admin/controller/basic/AdminBasicController.java, src/main/java/kr/co/sist/admin/controller/user/UserManageController.java, src/main/java/kr/co/sist/admin/dao/basic/AdminBasicDAO.java, src/main/java/kr/co/sist/admin/dao/user/UserManageDAO.java, src/main/java/kr/co/sist/admin/domain/user/UserInfoDomain.java, src/main/java/kr/co/sist/admin/service/basic/AdminBasicService.java, src/main/java/kr/co/sist/admin/service/user/UserManageService.java, src/main/java/kr/co/sist/admin/vo/basic/UpdateAdminInfoVO.java, src/main/java/kr/co/sist/admin/vo/user/SearchVO.java, src/main/java/kr/co/sist/mapper/admin/basic/adminMapper.xml, src/main/java/kr/co/sist/mapper/admin/user/userManageMapper.xml, src/main/java/kr/co/sist/properties/mybatis-config.xml, src/main/webapp/WEB-INF/views/assets/layout/admin/header.jsp, src/main/webapp/WEB-INF/views/assets/layout/admin/lib.jsp, src/main/webapp/WEB-INF/views/manage/admin/admins.jsp, src/main/webapp/WEB-INF/views/manage/adminLogin/adminLogin.jsp, src/main/webapp/WEB-INF/views/manage/index.jsp, src/main/webapp/WEB-INF/views/manage/user/users.jsp, src/main/webapp/assets/layout/admin/header.jsp, src/main/webapp/assets/layout/admin/lib.jsp
feat: 관리자 추가/수정 시 관리자 ID 중복 체크 기능 추가
=> feat: 관리자 추가/수정 시 관리자 ID 중복 체크 기능 추가
